// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyurteygfpsnuancgnkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5dXJ0ZXlnZnBzbnVhbmNnbmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODU5NzMsImV4cCI6MjA2NDY2MTk3M30.zHm0KfcsIZV3yf61I49U268W4HAEBNTjLCFzJrf2J_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);